import PDFDocument from "pdfkit";

export const generatePdf = (data) => {
    return new Promise((resolve, reject) => {

        const doc = new PDFDocument({
            size: "A4",

            margins: {
                top: 55,
                bottom: 65,
                left: 55,
                right: 55
            },

            info: {
                Author: "FridayAI",
                Title: data.title || "FridayAI Document",
                Creator: "FridayAI"
            }
        });

        const chunks = [];

        doc.on("data", (chunk) => chunks.push(chunk));

        doc.on("end", () => {
            resolve(Buffer.concat(chunks));
        });

        doc.on("error", reject);


        // ============================================
        // COLORS
        // ============================================

        const COLORS = {
            primary: "#111827",
            secondary: "#64748B",
            muted: "#94A3B8",
            accent: "#F97316",
            border: "#E2E8F0",
            bullet: "#F97316",
            body: "#334155"
        };


        // ============================================
        // PAGE HELPERS
        // ============================================

        const pageWidth = doc.page.width;
        const pageHeight = doc.page.height;

        const left = doc.page.margins.left;
        const right = pageWidth - doc.page.margins.right;

        const contentWidth = right - left;


        // ============================================
        // FOOTER
        // ============================================

        function drawFooter() {

            const oldBottomMargin = doc.page.margins.bottom;

            doc.page.margins.bottom = 0;

            const savedY = doc.y;

            const y = pageHeight - 42;

            // Footer line
            doc
                .save()
                .moveTo(left, y - 10)
                .lineTo(right, y - 10)
                .strokeColor(COLORS.border)
                .lineWidth(0.7)
                .stroke()
                .restore();


            // Footer left
            doc
                .font("Helvetica")
                .fontSize(8)
                .fillColor(COLORS.muted)
                .text(
                    "Generated by FridayAI",
                    left,
                    y,
                    {
                        width: contentWidth / 2,
                        align: "left"
                    }
                );


            // Footer right
            doc
                .font("Helvetica")
                .fontSize(8)
                .fillColor(COLORS.muted)
                .text(
                    new Date().toLocaleDateString(),
                    pageWidth / 2,
                    y,
                    {
                        width: contentWidth / 2,
                        align: "right"
                    }
                );


            doc.page.margins.bottom = oldBottomMargin;

            doc.y = savedY;
        }


        // Footer first page
        drawFooter();

        // Footer every new page
        doc.on("pageAdded", () => {
            drawFooter();
        });


        // ============================================
        // TITLE
        // ============================================

        const title = data.title || "FridayAI Document";

        doc
            .font("Helvetica-Bold")
            .fontSize(30)
            .fillColor(COLORS.primary)
            .text(
                title,
                left,
                doc.y,
                {
                    width: contentWidth,
                    align: "center",
                    lineGap: 2
                }
            );


        // ============================================
        // TITLE ACCENT LINE
        // ============================================

        doc.moveDown(0.55);

        const titleLineY = doc.y;

        doc
            .save()
            .strokeColor(COLORS.accent)
            .lineWidth(3)
            .moveTo(
                pageWidth / 2 - 45,
                titleLineY
            )
            .lineTo(
                pageWidth / 2 + 45,
                titleLineY
            )
            .stroke()
            .restore();


        // ============================================
        // SUBTITLE
        // ============================================

        const subtitle = data.subtitle || "";

        if (subtitle) {

            doc.moveDown(0.85);

            doc
                .font("Helvetica")
                .fontSize(13)
                .fillColor(COLORS.secondary)
                .text(
                    subtitle,
                    left,
                    doc.y,
                    {
                        width: contentWidth,
                        align: "center",
                        lineGap: 3
                    }
                );
        }


        // ============================================
        // INTRO DIVIDER
        // ============================================

        doc.moveDown(1.4);

        const dividerY = doc.y;

        doc
            .save()
            .moveTo(left, dividerY)
            .lineTo(right, dividerY)
            .strokeColor(COLORS.border)
            .lineWidth(0.8)
            .stroke()
            .restore();

        doc.moveDown(1.4);


        // ============================================
        // SECTIONS
        // ============================================

        const sections = Array.isArray(data.sections)
            ? data.sections
            : [];


        sections.forEach((section, index) => {

            const heading = section.heading || "";

            const points = Array.isArray(section.points)
                ? section.points
                : [];


            // ========================================
            // PAGE BREAK CHECK
            // ========================================

            const minimumSectionHeight = 100;

            const availableHeight =
                pageHeight -
                doc.page.margins.bottom -
                doc.y;


            if (
                availableHeight < minimumSectionHeight &&
                index !== 0
            ) {
                doc.addPage();
            }


            // ========================================
            // SECTION HEADING
            // ========================================

            const headingY = doc.y;

            doc
                .font("Helvetica-Bold")
                .fontSize(17)
                .fillColor(COLORS.primary)
                .text(
                    heading,
                    left,
                    headingY,
                    {
                        width: contentWidth,
                        align: "left",
                        lineGap: 2
                    }
                );


            // ========================================
            // HEADING UNDERLINE
            // ========================================

            doc.moveDown(0.35);

            const underlineY = doc.y;

            doc
                .save()
                .strokeColor(COLORS.accent)
                .lineWidth(2.5)
                .moveTo(
                    left,
                    underlineY
                )
                .lineTo(
                    left + 45,
                    underlineY
                )
                .stroke()
                .restore();


            // Space after underline
            doc.moveDown(0.75);


            // ========================================
            // BULLET POINTS
            // ========================================

            points.forEach((point) => {

                if (!point) return;


                // ------------------------------------
                // Check bottom space
                // ------------------------------------

                const bottomLimit =
                    pageHeight -
                    doc.page.margins.bottom -
                    20;


                if (doc.y > bottomLimit) {
                    doc.addPage();
                }


                // ------------------------------------
                // Bullet position
                // ------------------------------------

                const bulletX = left + 3;

                const textX = left + 18;

                const textWidth =
                    contentWidth - 18;

                const bulletY = doc.y + 6;


                // ------------------------------------
                // Bullet circle
                // ------------------------------------

                doc
                    .save()
                    .circle(
                        bulletX,
                        bulletY,
                        2.5
                    )
                    .fillColor(COLORS.bullet)
                    .fill()
                    .restore();


                // ------------------------------------
                // Bullet text
                // ------------------------------------

                doc
                    .font("Helvetica")
                    .fontSize(10.5)
                    .fillColor(COLORS.body)
                    .text(
                        point,
                        textX,
                        doc.y,
                        {
                            width: textWidth,
                            align: "left",
                            lineGap: 3
                        }
                    );


                // Space after bullet
                doc.moveDown(0.35);
            });


            // ========================================
            // SPACE AFTER SECTION
            // ========================================

            doc.moveDown(0.8);
        });


        // ============================================
        // END DOCUMENT
        // ============================================

        doc.end();
    });
};