import PDFDocument from "pdfkit";

export const generatePdf = (data) => {
    return new Promise((resolve, reject) => {

        const doc = new PDFDocument({
            size: "A4",

            margins: {
                top: 55,
                bottom: 65,
                left: 55,
                right: 55
            },

            info: {
                Author: "FridayAI",
                Title: data.title || "FridayAI Document",
                Creator: "FridayAI"
            }
        });

        const chunks = [];

        doc.on("data", (chunk) => chunks.push(chunk));

        doc.on("end", () => {
            resolve(Buffer.concat(chunks));
        });

        doc.on("error", reject);


        // ============================================
        // COLORS
        // ============================================

        const COLORS = {
            primary: "#111827",
            secondary: "#64748B",
            muted: "#94A3B8",
            accent: "#F97316",
            lightAccent: "#FFF7ED",
            border: "#E2E8F0",
            bullet: "#F97316"
        };


        // ============================================
        // PAGE HELPERS
        // ============================================

        const pageWidth = doc.page.width;
        const pageHeight = doc.page.height;

        const contentWidth =
            pageWidth -
            doc.page.margins.left -
            doc.page.margins.right;


        // ============================================
        // HEADER / FOOTER
        // ============================================

        function drawFooter() {

            const y = pageHeight - 42;

            doc
                .moveTo(
                    doc.page.margins.left,
                    y - 10
                )
                .lineTo(
                    pageWidth - doc.page.margins.right,
                    y - 10
                )
                .strokeColor(COLORS.border)
                .lineWidth(0.7)
                .stroke();

            doc
                .fontSize(8)
                .fillColor(COLORS.muted)
                .text(
                    "Generated by FridayAI",
                    doc.page.margins.left,
                    y,
                    {
                        width: contentWidth / 2,
                        align: "left"
                    }
                );

            doc
                .fontSize(8)
                .fillColor(COLORS.muted)
                .text(
                    `${new Date().toLocaleDateString()}`,
                    pageWidth / 2,
                    y,
                    {
                        width: contentWidth / 2,
                        align: "right"
                    }
                );
        }


        // Draw footer on every page
        drawFooter();

        doc.on("pageAdded", () => {
            drawFooter();
        });


        // ============================================
        // TITLE
        // ============================================

        doc
            .font("Helvetica-Bold")
            .fontSize(30)
            .fillColor(COLORS.primary)
            .text(
                data.title || "FridayAI Document",
                {
                    align: "center",
                    width: contentWidth
                }
            );


        // Orange accent line

        doc
            .moveDown(0.65)
            .save()
            .strokeColor(COLORS.accent)
            .lineWidth(3)
            .moveTo(
                pageWidth / 2 - 45,
                doc.y
            )
            .lineTo(
                pageWidth / 2 + 45,
                doc.y
            )
            .stroke()
            .restore();


        // ============================================
        // SUBTITLE
        // ============================================

        doc
            .moveDown(1.1)
            .font("Helvetica")
            .fontSize(13)
            .fillColor(COLORS.secondary)
            .text(
                data.subtitle || "",
                {
                    align: "center",
                    width: contentWidth,
                    lineGap: 3
                }
            );


        // ============================================
        // INTRO DIVIDER
        // ============================================

        doc.moveDown(1.6);

        doc
            .moveTo(
                doc.page.margins.left,
                doc.y
            )
            .lineTo(
                pageWidth - doc.page.margins.right,
                doc.y
            )
            .strokeColor(COLORS.border)
            .lineWidth(0.8)
            .stroke();


        doc.moveDown(1.5);


        // ============================================
        // SECTIONS
        // ============================================

        data.sections.forEach((section, index) => {

            const heading = section.heading || "";
            const points = Array.isArray(section.points)
                ? section.points
                : [];


            // ----------------------------------------
            // Check available space
            // ----------------------------------------

            const estimatedHeight =
                75 + points.length * 32;

            const availableHeight =
                pageHeight -
                doc.page.margins.bottom -
                doc.y;

            if (
                availableHeight < estimatedHeight &&
                index !== 0
            ) {
                doc.addPage();
            }


            // ----------------------------------------
            // Section heading
            // ----------------------------------------

            doc
                .font("Helvetica-Bold")
                .fontSize(17)
                .fillColor(COLORS.primary)
                .text(
                    heading,
                    {
                        width: contentWidth,
                        lineGap: 2
                    }
                );


            // Orange underline

            doc
                .moveDown(0.35)
                .save()
                .strokeColor(COLORS.accent)
                .lineWidth(2.5)
                .moveTo(
                    doc.page.margins.left,
                    doc.y
                )
                .lineTo(
                    doc.page.margins.left + 42,
                    doc.y
                )
                .stroke()
                .restore();


            // Space between heading and bullets

            doc.moveDown(0.75);


            // ----------------------------------------
            // Bullet points
            // ----------------------------------------

            points.forEach((point) => {

                if (!point) return;

                const bulletX =
                    doc.page.margins.left + 3;

                const textX =
                    doc.page.margins.left + 18;

                const textWidth =
                    contentWidth - 18;


                // Bullet circle

                doc
                    .circle(
                        bulletX,
                        doc.y + 6,
                        2.5
                    )
                    .fillColor(COLORS.bullet)
                    .fill();


                // Bullet text

                doc
                    .font("Helvetica")
                    .fontSize(10.5)
                    .fillColor("#334155")
                    .text(
                        point,
                        textX,
                        doc.y,
                        {
                            width: textWidth,
                            lineGap: 3,
                            paragraphGap: 5
                        }
                    );


                // Extra spacing after bullet

                doc.moveDown(0.35);
            });


            // ----------------------------------------
            // Space after section
            // ----------------------------------------

            doc.moveDown(0.75);
        });


        // ============================================
        // END DOCUMENT
        // ============================================

        doc.end();
    });
};